### ISSUE TITLE
Build error: "not a valid python or it is missing distutils"

### ISSUE THREAD

**Issue by slightlyfaulty** [libratbag/libratbag#1410]
I keep getting this error when I try to build master on Arch:

```
../meson.build:498:0: ERROR: <PythonExternalProgram 'python3' -> ['/usr/bin/python']> is not a valid python or it is missing distutils
```

I've installed the `python-setuptools` and `python3-distutils` packages but it doesn't seem to make a difference.

Any ideas?

[meson-log.txt](https://github.com/libratbag/libratbag/files/10453351/meson-log.txt)

**Comment by staticssleever668** [comment]
Could you try installing all dependencies from the PKGBUILD of libratbag-git?
`sudo pacman -S --asdeps --needed glib2 libevdev libudev.so libunistring json-glib python python-evdev meson swig git check valgrind python-gobject python-lxml`
(note: this is without `python-sphinx python-sphinx_rtd_theme` used for building documentation, which is disabled by default)

**Comment by eli-schwartz** [comment]
```
Could not introspect Python (['/usr/bin/python', '/tmp/tmpemeqq6km.py']): exit code 1
Program stdout:


Program stderr:

Traceback (most recent call last):
  File "/tmp/tmpemeqq6km.py", line 66, in <module>
    'link_libpython': links_against_libpython(),
  File "/tmp/tmpemeqq6km.py", line 41, in links_against_libpython
    cmd = Distribution().get_command_obj('build_ext')
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 475, in __init__
    _Distribution.__init__(
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 898, in finalize_options
    for ep in sorted(loaded, key=by_order):
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 897, in <lambda>
    loaded = map(lambda e: e.load(), filtered)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools_scm'
```

So:
- you have setuptools installed, this hijacked distutils so that `import distutils` actually imports `setuptools._distutils`
- setuptools itself is apparently broken -- it thinks setuptools_scm is installed and wants to use it, but that isn't actually installed (or at least cannot be imported)

> I've installed the `python-setuptools` and `python3-distutils` packages but it doesn't seem to make a difference.

BTW: python-setuptools is the Debian name for a python2 thing (and the Arch name for a python3 thing), and python3-distutils is the Debian name for -- as the name implies -- a python3 thing.

No other distros really *provide* a distutils package in the first place, because they do what they are supposed to do and include distutils in the stdlib. I am somewhat curious how you were able to install something called "python3-distutils" on an Arch system.

**Comment by slightlyfaulty** [comment]
Sorry, it was `python-distutils-extra` not `python3-distutils`. I removed `python-setuptools` and `python-distutils-extra` and it built without error. Thanks for the tip!
