### ISSUE TITLE
Crashes. G502 SE HERO Gaming Mouse

### ISSUE THREAD

**Issue by uriid1** [libratbag/libratbag#1581]
**Information**
- ratbagd version 0.17
- Kernel version: Linux 6.6.10-1-MANJARO x86_64 GNU/Linux

Device info:
```
$ ratbagctl G502 info
hooting-chinchilla - Logitech G502 HERO Gaming Mouse
             Model: usb:046d:c08b:0
 Number of Buttons: 11
    Number of Leds: 2
Number of Profiles: 5
Profile 0:
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 1200dpi
    1: 2400dpi (active) (default)
    2: 3200dpi
    3: 1100dpi
    4: 0dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'resolution-alternate'
  Button: 6 is mapped to macro '↓LEFTCTRL ↕Z ↑LEFTCTRL'
  Button: 7 is mapped to macro '↓LEFTCTRL ↕Y ↑LEFTCTRL'
  Button: 8 is mapped to 'resolution-cycle-up'
  Button: 9 is mapped to macro '↕RIGHT'
  Button: 10 is mapped to macro '↕LEFT'
  LED: 0, depth: rgb, mode: off
  LED: 1, depth: rgb, mode: off
Profile 1: (disabled) (active)
Profile 2: (disabled)
Profile 3: (disabled)
Profile 4: (disabled)

$ udevadm info -n /dev/hidraw6
P: /devices/pci0000:00/0000:00:08.1/0000:0e:00.3/usb7/7-4/7-4:1.1/0003:046D:C08B.0007/hidraw/hidraw6
M: hidraw6
R: 6
U: hidraw
D: c 240:6
N: hidraw6
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:08.1/0000:0e:00.3/usb7/7-4/7-4:1.1/0003:046D:C08B.0007/hidraw/hidraw6
E: DEVNAME=/dev/hidraw6
E: MAJOR=240
E: MINOR=6
E: SUBSYSTEM=hidraw
E: USEC_INITIALIZED=5326795
E: ID_PATH_WITH_USB_REVISION=pci-0000:0e:00.3-usbv2-0:4:1.1
E: ID_PATH=pci-0000:0e:00.3-usb-0:4:1.1
E: ID_PATH_TAG=pci-0000_0e_00_3-usb-0_4_1_1
E: ID_FOR_SEAT=hidraw-pci-0000_0e_00_3-usb-0_4_1_1
E: TAGS=:Logitech_G502_Hero_Gaming_Mouse:uaccess:seat:udev-acl:
E: CURRENT_TAGS=:Logitech_G502_Hero_Gaming_Mouse:uaccess:seat:udev-acl:
```

**Describe the bug**
The program crashes after pressing any button (GUI).
For example, it crashed when I tried to switch profiles. Or when I changed the DPI value.
About six months ago, I used this program, and there were no issues.

Example (change profile):
```
$ piper
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/piper/ratbagd.py", line 217, in _dbus_call
    res = self._proxy.call_sync(method, val,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: Время ожидания истекло (24)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/piper/mouseperspective.py", line 128, in _on_profile_row_activated
    row.set_active()
  File "/usr/lib/python3.11/site-packages/piper/profilerow.py", line 42, in set_active
    self._profile.set_active()
  File "/usr/lib/python3.11/site-packages/piper/ratbagd.py", line 534, in set_active
    ret = self._dbus_call("SetActive", "")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/piper/ratbagd.py", line 225, in _dbus_call
    raise RatbagdDBusTimeout(e.message)
piper.ratbagd.RatbagdDBusTimeout: Время ожидания истекло
```

**Logs**
```
$ ratbagd --verbose=raw
ratbag raw: hidpp read:   11 ff 02 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 02 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 02 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 02 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 02 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 02 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 02 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 02 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
...
```

**Additional context**

**Comment by staticssleever668** [comment]
Hi!

> Logs

This seems to be just a chunk of the logs, or are you saying it gets stuck in a loop printing this?
