### ISSUE TITLE
g502x plus

### ISSUE THREAD

**Issue by popcornman209** [libratbag/libratbag#1627]
**Is your feature request related to a problem? Please describe.**
yes, my g502x plus mouse doesnt work, it just says "no devices found" on piper and ratbagctl. ive tried using the wireless dongle and the wired cable.

**Describe the solution you'd like**
the g502x plus mouse to work

**Describe alternatives you've considered**
none

![image](https://github.com/libratbag/libratbag/assets/135404395/b23fb5f4-d046-4182-8015-27d0132a30ec)

**Comment by MOVZX** [comment]
Set proper driver index for the USB receiver, fixed mine here: https://github.com/MOVZX/libratbag/commit/53d447dc81c69a516c53aa713d491a3cacec333a

**Comment by MOVZX** [comment]
> @MOVZX feel free to make a PR if that helps. Such change was also suggested in #1623.

Works for both wired and wireless

```
$ ratbagctl singing-gundi info
singing-gundi - Logitech G502 X PLUS
             Model: usb:046d:c095:0
       Device Type: Mouse
 Number of Buttons: 11
    Number of Leds: 1
Number of Profiles: 5
Profile 0:
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 200dpi
    1: 400dpi
    2: 500dpi (active) (default)
    3: 800dpi
    4: 1000dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 5'
  Button: 4 is mapped to macro '↕KEY_PLAYPAUSE'
  Button: 5 is mapped to 'button 4'
  Button: 6 is mapped to macro '↕KEY_PREVIOUSSONG'
  Button: 7 is mapped to macro '↕KEY_NEXTSONG'
  Button: 8 is mapped to 'profile-cycle-up'
  Button: 9 is mapped to 'button 1'
  Button: 10 is mapped to macro '↕KEY_MIN_INTERESTING'
  LED: 0, depth: rgb, mode: breathing, color: ff0000, duration: 5000, brightness: 142
Profile 1:
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 200dpi
    1: 450dpi
    2: 500dpi (active) (default)
    3: 800dpi
    4: 1000dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 5'
  Button: 4 is mapped to macro '↕KEY_B'
  Button: 5 is mapped to 'button 4'
  Button: 6 is mapped to macro '↕KEY_F5'
  Button: 7 is mapped to macro '↕KEY_F3'
  Button: 8 is mapped to 'profile-cycle-up'
  Button: 9 is mapped to 'button 2'
  Button: 10 is mapped to macro '↕KEY_F4'
  LED: 0, depth: rgb, mode: breathing, color: ff0000, duration: 3000, brightness: 140
Profile 2: (disabled) (active)
Profile 3: (disabled)
Profile 4: (disabled)
```

**Comment by popcornman209** [comment]
> Set proper driver index for the USB receiver, fixed mine here: [MOVZX@53d447d](https://github.com/MOVZX/libratbag/commit/53d447dc81c69a516c53aa713d491a3cacec333a)

i have absolutely zero clue how to do that, and when running the command you have it just cant find the device (also running "ratbagctl list" returns no devices available)

**Comment by MOVZX** [comment]
> > Set proper driver index for the USB receiver, fixed mine here: [MOVZX@53d447d](https://github.com/MOVZX/libratbag/commit/53d447dc81c69a516c53aa713d491a3cacec333a)
> 
> i have absolutely zero clue how to do that, thats just a bunch of buzzwords for me lol. also when running the command you have it just cant find the device (also running "ratbagctl list" returns no devices available)
> 
> i made that file you mentioned, put the usb id in there (which i think i did right? there was only one for me), restarted ratbagd and listed devices, still nothing.
> 

Try build using my fork: https://github.com/MOVZX/libratbag/commits/master/

**Comment by popcornman209** [comment]
i built it (not sure if i did it right but i think i did) and im getting this when running ratbagctl:
`Traceback (most recent call last):
  File "/usr/local/bin/ratbagctl", line 3184, in <module>
    ret = main(sys.argv[1:])
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/ratbagctl", line 3163, in main
    _r = open_ratbagd(verbose=cmd.verbose)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/ratbagctl", line 3129, in open_ratbagd
    ratbagd = Ratbagd(RATBAGD_API_VERSION)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/ratbagctl", line 300, in __init__
    raise RatbagdIncompatibleError(self.api_version or -1, api_version)
RatbagdIncompatibleError: ratbagd API version is 1 but we require 2`

**Comment by MOVZX** [comment]
> i built it (not sure if i did it right but i think i did) and im getting this when running ratbagctl:
> 
> ```
>   File "/usr/local/bin/ratbagctl", line 3184, in <module>
>     ret = main(sys.argv[1:])
>           ^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/ratbagctl", line 3163, in main
>     _r = open_ratbagd(verbose=cmd.verbose)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/ratbagctl", line 3129, in open_ratbagd
>     ratbagd = Ratbagd(RATBAGD_API_VERSION)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/ratbagctl", line 300, in __init__
>     raise RatbagdIncompatibleError(self.api_version or -1, api_version)
> RatbagdIncompatibleError: ratbagd API version is 1 but we require 2```
> ```

What's your distro? I'm using Arch.

**Comment by popcornman209** [comment]
> What's your distro? I'm using Arch.
same here, not sure whats causing it maybe i built it wrong or something.

**Comment by MOVZX** [comment]
Before you install the newly built package, make sure to stop ratbagd daemon first:
> sudo systemctl stop ratbagd.service

**Comment by MOVZX** [comment]
### **Connected through USB-C Dongle**
![Screenshot_20240729_113143](https://github.com/user-attachments/assets/9713ff4b-a4ff-4e5b-891f-4d7c019c6bb8)

### **Connected through USB-C Cable**
![Screenshot_20240729_113219](https://github.com/user-attachments/assets/451211b5-452b-43be-a77e-1da5bd7233ac)

**Comment by popcornman209** [comment]
just stopped it, re built it, and same error when running ratbagctl

**Comment by MOVZX** [comment]
Not sure if it's allowed, but I attached my built file here just in case you wanna try.

`sudo pacman -U libratbag-0.20-2-x86_64.pkg.tar.zst`

[libratbag.zip](https://github.com/user-attachments/files/16407528/libratbag.zip)

**Comment by popcornman209** [comment]
ratbagctl works now, and the device shows up so thats good. for some reason now piper is getting the incompatible ratbag api version error now tho. not sure how to fix that.
![image](https://github.com/user-attachments/assets/ecb18026-f2a4-451c-ac5e-9be322c0cb39)

**Comment by MOVZX** [comment]
Try recompile Piper maybe.

I don't use Piper, I use bash script to setup my mouse.

**Comment by popcornman209** [comment]
yeah im just going to use ratbagctl, it does everything i need it to so no point getting the piper working lol.

**Comment by popcornman209** [comment]
> You needed to restart ratbagd. `systemctl restart ratbagd.service`.
weirdly i tried that a few times but it didnt fix it, either way it works now so who knows.

**Comment by mjugger** [comment]
Hi,
Can we get a PR for this change?

**Comment by LMarshallAfzal** [comment]
I added the new .device file for the mouse which did make an improvment however. However when I check device info it only has 3 profiles when it should have 5, DPI resolution is not included.

*logitech-g502-x-plus-wireless*
```
Device]
Name=Logitech G502 X Plus Wireless
DeviceMatch=usb:046d:c095;usb:046d:c547
Driver=hidpp20

[Driver/hidpp20]
DeviceIndex=1
Profiles=3
Buttons=11
```

*stdout of ratbagctl info*
```
warbling-mara - Logitech USB Receiver
             Model: usb:046d:c547:0
 Number of Buttons: 11
    Number of Leds: 2
Number of Profiles: 3
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Button: 0 is mapped to macro '↕F1'
  Button: 1 is mapped to macro '↕F2'
  Button: 2 is mapped to macro '↕F3'
  Button: 3 is mapped to macro '↕F4'
  Button: 4 is mapped to macro '↕F5'
  Button: 5 is mapped to macro '↕F6'
  Button: 6 is mapped to macro '↕F7'
  Button: 7 is mapped to macro '↕F8'
  Button: 8 is mapped to macro '↕F9'
  Button: 9 is mapped to macro '↕F10'
  Button: 10 is mapped to macro '↕F11'
  LED: 0, depth: rgb, mode: cycle, duration: 5000, brightness: 255
  LED: 1, depth: rgb, mode: off
Profile 1:
  Name: n/a
  Report Rate: 1000Hz
  Button: 0 is mapped to macro '↕F1'
  Button: 1 is mapped to macro '↕F2'
  Button: 2 is mapped to macro '↕F3'
  Button: 3 is mapped to macro '↕F4'
  Button: 4 is mapped to macro '↕F5'
  Button: 5 is mapped to macro '↕F6'
  Button: 6 is mapped to macro '↕F7'
  Button: 7 is mapped to macro '↕F8'
  Button: 8 is mapped to macro '↕F9'
  Button: 9 is mapped to macro '↕F10'
  Button: 10 is mapped to macro '↕F11'
  LED: 0, depth: rgb, mode: breathing, color: 00dcff, duration: 3000, brightness: 255
  LED: 1, depth: rgb, mode: breathing, color: 00dcff, duration: 3000, brightness: 255
Profile 2:
  Name: n/a
  Report Rate: 1000Hz
  Button: 0 is mapped to macro '↕F1'
  Button: 1 is mapped to macro '↕F2'
  Button: 2 is mapped to macro '↕F3'
  Button: 3 is mapped to macro '↕F4'
  Button: 4 is mapped to macro '↕F5'
  Button: 5 is mapped to macro '↕F6'
  Button: 6 is mapped to macro '↕F7'
  Button: 7 is mapped to macro '↕F8'
  Button: 8 is mapped to macro '↕F9'
  Button: 9 is mapped to macro '↕F10'
  Button: 10 is mapped to macro '↕F11'
  LED: 0, depth: rgb, mode: cycle, duration: 3000, brightness: 255
  LED: 1, depth: rgb, mode: off
```
I am also receiving the following errors in the service after I restarted the daemon.

*stdout of sytemctl ratbagd status*
```
● ratbagd.service - Daemon to introspect and modify configurable mice
     Loaded: loaded (/usr/lib/systemd/system/ratbagd.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Sun 2024-09-15 20:16:31 BST; 40s ago
   Main PID: 39204 (ratbagd)
      Tasks: 1 (limit: 19022)
     Memory: 760.0K
        CPU: 49ms
     CGroup: /system.slice/ratbagd.service
             └─39204 /usr/bin/ratbagd

Sep 15 20:16:31 nobara-pc systemd[1]: Starting ratbagd.service - Daemon to introspect and modify configurabl>
Sep 15 20:16:31 nobara-pc systemd[1]: Started ratbagd.service - Daemon to introspect and modify configurable>
Sep 15 20:16:33 nobara-pc ratbagd[39204]: ratbag error: Profile layout not supported: 0x05.
Sep 15 20:16:33 nobara-pc ratbagd[39204]: ratbag error: Logitech USB Receiver: error opening hidraw node (Op>
Sep 15 20:16:34 nobara-pc ratbagd[39204]: ratbag error: Profile layout not supported: 0x05.
Sep 15 20:16:34 nobara-pc ratbagd[39204]: ratbag error: Logitech USB Receiver: error opening hidraw node (Op>
Sep 15 20:16:34 nobara-pc ratbagd[39204]: ratbag error: Profile layout not supported: 0x05.
Sep 15 20:16:34 nobara-pc ratbagd[39204]: ratbag error: Logitech USB Receiver: error opening hidraw node (Op>
```
Any idea how to get around this?

**Comment by moxSedai** [comment]
I am unable to have piper or ratbagd see all 11 buttons, even with 11 buttons being listed in the device file and with changes made to have it pick up the mouse at all.

**Comment by mszumko** [comment]
Thanks @MOVZX 
I was tried to add device from hand but that didn't work.
But libratbag from ur repo works fine with my G502 X PLUS.

```
[mikszu@archlinux ~]$ ratbagctl list
hollering-marmot:    Logitech USB Receiver           
[mikszu@archlinux ~]$ ratbagctl hollering-marmot info
hollering-marmot - Logitech USB Receiver
             Model: usb:046d:c547:0
       Device Type: Mouse
 Number of Buttons: 11
    Number of Leds: 1
Number of Profiles: 5
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 800dpi
    1: 800dpi
    2: 800dpi (active) (default)
    3: 800dpi
    4: 800dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'resolution-alternate'
  Button: 5 is mapped to 'button 5'
  Button: 6 is mapped to 'wheel-left'
  Button: 7 is mapped to 'wheel-right'
  Button: 8 is mapped to 'profile-cycle-up'
  Button: 9 is mapped to 'resolution-up'
  Button: 10 is mapped to 'resolution-down'
  LED: 0, depth: rgb, mode: on, color: 23ebeb
Profile 1:
  Name: n/a
  Report Rate: 500Hz
  Resolutions:
    0: 800dpi
    1: 800dpi (active)
    2: 800dpi (default)
    3: 800dpi
    4: 800dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'second-mode'
  Button: 5 is mapped to 'button 5'
  Button: 6 is mapped to 'wheel-left'
  Button: 7 is mapped to 'wheel-right'
  Button: 8 is mapped to 'profile-cycle-up'
  Button: 9 is mapped to 'resolution-up'
  Button: 10 is mapped to 'resolution-down'
  LED: 0, depth: rgb, mode: on, color: eb23cd
Profile 2: (disabled)
Profile 3: (disabled)
Profile 4: (disabled)
```
