### ISSUE TITLE
RatbagdIncompatibleError: ratbagd API version is 1 but we require 2

### ISSUE THREAD

**Issue by sceddd** [libratbag/libratbag#1651]
- `ratbagd` version (`ratbagd --version`): 0.18
- Distribution: 
- Kernel version (ex. `uname -srmo`): Linux 6.8.0-45-generic x86_64 GNU/Linux

Device info (if applicable):
```
$ ratbagctl <device> info
OUTPUT HERE
```

**Describe the bug**
RatbagdIncompatibleError: ratbagd API version is 1 but we require 2
**To Reproduce**
I tried to download ratbagd from git but nothing displayed on piper
So I tried to use ratbagd command and this error show up:
RatbagdIncompatibleError: ratbagd API version is 1 but we require 2
By following #1634 I tried to reinstalled with flashpak and followed #1388 to install the old-version but the issue still there
**Logs**
this is the output of my flashpak
```
Name                                             Application ID                                        Version            Branch                Installation
Piper                                            org.freedesktop.Piper                                 0.7                stable                system
Mesa                                             org.freedesktop.Platform.GL.default                   24.0.9             22.08                 system
Mesa (Extra)                                     org.freedesktop.Platform.GL.default                   24.0.9             22.08-extra           system
Mesa                                             org.freedesktop.Platform.GL.default                   24.2.3             23.08                 system
Mesa (Extra)                                     org.freedesktop.Platform.GL.default                   24.2.3             23.08-extra           system
nvidia-550-100                                   org.freedesktop.Platform.GL.nvidia-550-100                               1.4                   system
Intel                                            org.freedesktop.Platform.VAAPI.Intel                                     22.08                 system
Intel                                            org.freedesktop.Platform.VAAPI.Intel                                     23.08                 system
openh264                                         org.freedesktop.Platform.openh264                     2.1.0              2.2.0                 system
GNOME Application Platform version 43            org.gnome.Platform                                                       43                    system
GNOME Application Platform version 45            org.gnome.Platform                                                       45                    system
Yaru Gtk Theme                                   org.gtk.Gtk3theme.Yaru                                                   3.22                  system
Yaru-prussiangreen-dark Gtk Theme                org.gtk.Gtk3theme.Yaru-prussiangreen-dark                                3.22                  system
```
```
$ ratbagd --verbose=raw
Starting ratbagd version 0.18 (API version 2)
Initializing libratbag
ratbag debug: New device: Logitech G733 Gaming Headset
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xab5
ratbag debug: Logitech G733 Gaming Headset is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 08
ratbag debug: - HID report ID 11
ratbag debug: - HID report ID ff
ratbag debug: - HID report ID 90
ratbag debug: - HID report ID 90
ratbag debug: - HID report ID c4
ratbag debug: - HID report ID c4
ratbag debug: - HID report ID ff
ratbag debug: - HID report ID e2
ratbag debug: hidpp: device supports long reports
ratbag raw: hidpp write:  11 ff 00 18 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 00 18 04 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 00 08 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 00 08 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0001 is at 0x01
ratbag raw: hidpp write:  11 ff 01 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 01 08 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 01 18 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 01 18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 01 18 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 01 18 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 01 18 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 01 18 80 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 01 18 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 01 18 80 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 01 18 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 01 18 83 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 01 18 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 01 18 83 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 01 18 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 01 18 1f 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag debug: 'Logitech G733 Gaming Headset' is using protocol v4.2
ratbag raw: 'Logitech G733 Gaming Headset' has 9 features
ratbag raw: Init feature HIDPP_PAGE_ROOT (0x0000)
ratbag raw: hidpp write:  11 ff 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0000 is at 0x00
ratbag raw: Init feature HIDPP_PAGE_FEATURE_SET (0x0001)
ratbag raw: hidpp write:  11 ff 00 08 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 00 08 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0001 is at 0x01
ratbag raw: Init feature HIDPP_PAGE_DEVICE_INFO (0x0003)
ratbag raw: hidpp write:  11 ff 00 08 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 00 08 02 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0003 is at 0x02
ratbag raw: unknown feature 0x0003
ratbag raw: Init feature HIDPP_PAGE_DEVICE_NAME (0x0005)
ratbag raw: hidpp write:  11 ff 00 08 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 00 08 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0005 is at 0x03
ratbag raw: unknown feature 0x0005
ratbag raw: Init feature HIDPP_PAGE_COLOR_LED_EFFECTS (0x8070)
ratbag raw: hidpp write:  11 ff 00 08 80 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 00 08 04 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x8070 is at 0x04
ratbag debug: device has color effects
ratbag raw: Init feature 0x8010 (0x8010)
ratbag raw: hidpp write:  11 ff 00 08 80 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 00 08 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x8010 is at 0x05
ratbag raw: unknown feature 0x8010
ratbag raw: Init feature 0x8310 (0x8310)
ratbag raw: hidpp write:  11 ff 00 08 83 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 00 08 06 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x8310 is at 0x06
ratbag raw: unknown feature 0x8310
ratbag raw: Init feature 0x8300 (0x8300)
ratbag raw: hidpp write:  11 ff 00 08 83 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 00 08 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x8300 is at 0x07
ratbag raw: unknown feature 0x8300
ratbag raw: Init feature 0x1f20 (0x1f20)
ratbag raw: hidpp write:  11 ff 00 08 1f 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 00 08 08 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1f20 is at 0x08
ratbag raw: unknown feature 0x1f20
ratbag raw: hidpp write:  11 ff 04 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff ff 04 08 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag error:     HID++ error from the device (255): ERR_LOGITECH_INTERNAL (05)
ratbag debug: driver match found: Logitech HID++2.0
hidraw2: "Logitech G733 Gaming Headset", 1 profiles
ratbag debug: New device: MSI MysticLight MS-1562
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 1462:1564
ratbag debug: New device: PNP0C50:00 06CB:7E7E
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 06cb:7e7e
DBus server ready
```

**Comment by sceddd** [comment]
it's look like there are some conflict here, I can see that the ratbagd is using API version 2 but the version when running ratbagd list output is version 1...
Any idea?

**Comment by sceddd** [comment]
> Hi! Is the error message actually "RatbagdIncompatibleError: ratbagd API version is 2 but we require 1"? Since you seem to be running latest libratbag v0.18 with older Piper 0.7. Right now libratbag v0.18 is only compatible with Piper 0.8, but currently Flathub only has Piper 0.7. For the time being, I suggest installing both libratbag and Piper from your distro's repo.

I have follow with your solution but the issue is still there, I tried to download from git, 
command:
```
git clone https://github.com/libratbag/piper.git
cd piper
meson builddir --prefix=/usr/
```
log:
```
...
piper 0.8

  User defined options
    prefix: /usr/

Found ninja-1.11.1 at /usr/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```
error for detail
```
ratbagctl list
Traceback (most recent call last):
  File "/usr/local/bin/ratbagctl", line 3184, in <module>
    ret = main(sys.argv[1:])
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/ratbagctl", line 3163, in main
    _r = open_ratbagd(verbose=cmd.verbose)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/ratbagctl", line 3129, in open_ratbagd
    ratbagd = Ratbagd(RATBAGD_API_VERSION)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/ratbagctl", line 300, in __init__
    raise RatbagdIncompatibleError(self.api_version or -1, api_version)
RatbagdIncompatibleError: ratbagd API version is 1 but we require 2
```
