### ISSUE TITLE
ratbagd segfaults on start

### ISSUE THREAD

**Issue by phomes** [libratbag/libratbag#311]
I am probably doing something wrong. Ratbagd will segfault for me no matter how I try to start it:

```
Process 5279 (ratbagd) of user 0 dumped core.

Stack trace of thread 5279:
#0  0x00007f0ac861d40d g_slice_alloc (libglib-2.0.so.0)
#1  0x00007f0ac85f6d64 g_key_file_flush_parse_buffer (libglib-2.0.so.0)
#2  0x00007f0ac85f71ce g_key_file_parse_data (libglib-2.0.so.0)
#3  0x00007f0ac85f73b1 g_key_file_load_from_fd (libglib-2.0.so.0)
#4  0x00007f0ac85f7d52 g_key_file_load_from_file (libglib-2.0.so.0)
#5  0x0000000000417183 file_data_matches (ratbagd)
#6  0x0000000000417606 ratbag_device_data_new_for_id (ratbagd)
#7  0x0000000000413b72 ratbag_device_new (ratbagd)
#8  0x00000000004143a8 ratbag_device_new_from_udev_device (ratbagd)
#9  0x0000000000404244 ratbagd_process_device (ratbagd)
#10 0x0000000000404938 ratbagd_run_enumerate (ratbagd)
#11 0x00000000004049d9 ratbagd_run (ratbagd)
#12 0x0000000000404af6 main (ratbagd)
#13 0x00007f0ac7eef50a __libc_start_main (libc.so.6)
#14 0x0000000000402b5a _start (ratbagd)
```

This is just from:
$ meson builddir --prefix=/usr/
$ ninja -C builddir
$ sudo ninja -C builddir install
$ sudo ratbagd

**Comment by phomes** [comment]
I will debug this further. It only happens on the G9. Not the G300. Also, if ratbagd is already running and I plug in the G9 then it's 50/50 if it crashes or not

**Comment by phomes** [comment]
When the mouse is already plugged strace gives me this:
```
open("/usr/share/libratbag", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 8
fstat(8, {st_mode=S_IFDIR|0755, st_size=1448, ...}) = 0
getdents(8, /* 33 entries */, 32768)    = 1488
getdents(8, /* 0 entries */, 32768)     = 0
close(8)                                = 0
open("/usr/share/libratbag/roccat-kone-xtd.device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=94, ...}) = 0
read(8, "[Device]\nName=Roccat Kone XTD\nDe"..., 4096) = 94
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g9x-[Original].device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=230, ...}) = 0
read(8, "# Logitech G9x [Original]\n# http"..., 4096) = 230
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g9x-[Call-of-Duty-MW3-Edition].device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=271, ...}) = 0
read(8, "# Logitech G9x [Call of Duty MW3"..., 4096) = 271
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g900.device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=116, ...}) = 0
read(8, "# Logitech G900 over USB\n[Device"..., 4096) = 116
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g900-wireless.device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=172, ...}) = 0
read(8, "# Logitech G900 and G403 over wi"..., 4096) = 172
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g9.device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=276, ...}) = 0
read(8, "# Logitech G9\n# http://support.l"..., 4096) = 276
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g700s.device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=273, ...}) = 0
read(8, "# Logitech G700s over USB\n# http"..., 4096) = 273
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g700s-wireless.device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=296, ...}) = 0
read(8, "# Logitech G700s over wireless U"..., 4096) = 296
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g700.device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=261, ...}) = 0
read(8, "# Logitech G700 over USB\n# http:"..., 4096) = 261
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g700-wireless.device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=262, ...}) = 0
read(8, "# Logitech G700 over wireless US"..., 4096) = 262
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g7.device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=184, ...}) = 0
read(8, "# Logitech G7\n# http://support.l"..., 4096) = 184
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault
```

If I start it with the mouse unplugged and then insert/remove it a few times I get this:
```
open("/usr/share/libratbag", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 8
fstat(8, {st_mode=S_IFDIR|0755, st_size=1448, ...}) = 0
getdents(8, /* 33 entries */, 32768)    = 1488
getdents(8, /* 0 entries */, 32768)     = 0
close(8)                                = 0
open("/usr/share/libratbag/roccat-kone-xtd.device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=94, ...}) = 0
read(8, "[Device]\nName=Roccat Kone XTD\nDe"..., 4096) = 94
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g9x-[Original].device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=230, ...}) = 0
read(8, "# Logitech G9x [Original]\n# http"..., 4096) = 230
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g9x-[Call-of-Duty-MW3-Edition].device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=271, ...}) = 0
read(8, "# Logitech G9x [Call of Duty MW3"..., 4096) = 271
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g900.device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=116, ...}) = 0
read(8, "# Logitech G900 over USB\n[Device"..., 4096) = 116
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g900-wireless.device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=172, ...}) = 0
read(8, "# Logitech G900 and G403 over wi"..., 4096) = 172
read(8, "", 4096)                       = 0
close(8)                                = 0
open("/usr/share/libratbag/logitech-g9.device", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=276, ...}) = 0
read(8, "# Logitech G9\n# http://support.l"..., 4096) = 276
read(8, "", 4096)                       = 0
close(8)                                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x3947} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault

```

**Comment by phomes** [comment]
building with address sanitizer gives:
```
ASAN:DEADLYSIGNAL
=================================================================
==9603==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f35ce91540d bp 0x000000000001 sp 0x7ffe97db2a80 T0)
==9603==The signal is caused by a READ memory access.
==9603==Hint: address points to the zero page.
    #0 0x7f35ce91540c in g_slice_alloc (/lib64/libglib-2.0.so.0+0x6740c)
    #1 0x7f35ce8eed63  (/lib64/libglib-2.0.so.0+0x40d63)
    #2 0x7f35ce8ef1cd  (/lib64/libglib-2.0.so.0+0x411cd)
    #3 0x7f35ce8ef3b0  (/lib64/libglib-2.0.so.0+0x413b0)
    #4 0x7f35ce8efd51 in g_key_file_load_from_file (/lib64/libglib-2.0.so.0+0x41d51)
    #5 0x4390ef in file_data_matches ../src/libratbag-data.c:248
    #6 0x439d7e in ratbag_device_data_new_for_id ../src/libratbag-data.c:342
    #7 0x42f9a8 in ratbag_device_new ../src/libratbag.c:184
    #8 0x430b72 in ratbag_device_new_from_udev_device ../src/libratbag.c:438
    #9 0x405cdc in ratbagd_process_device ../ratbagd/ratbagd.c:427
    #10 0x405f08 in ratbagd_monitor_event ../ratbagd/ratbagd.c:464
    #11 0x7f35cff0811f  (/lib64/libsystemd.so.0+0x2911f)
    #12 0x7f35cff084f9 in sd_event_dispatch (/lib64/libsystemd.so.0+0x294f9)
    #13 0x7f35cff08676 in sd_event_run (/lib64/libsystemd.so.0+0x29676)
    #14 0x7f35cff0884a in sd_event_loop (/lib64/libsystemd.so.0+0x2984a)
    #15 0x406e70 in ratbagd_run ../ratbagd/ratbagd.c:701
    #16 0x4070d3 in main ../ratbagd/ratbagd.c:726
    #17 0x7f35ce1e7509 in __libc_start_main (/lib64/libc.so.6+0x20509)
    #18 0x403399 in _start (/home/phomes/libratbag/builddir/ratbagd+0x403399)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib64/libglib-2.0.so.0+0x6740c) in g_slice_alloc
==9603==ABORTING
```

This is with glib 2.52.3 from fedora 26
