### ISSUE TITLE
Trying to compile libratbag on Ubuntu 18.04

### ISSUE THREAD

**Issue by dgroos** [libratbag/libratbag#476]
In trying to compile libratbag on Ubuntu 18.04 with:
```
git clone https://github.com/libratbag/libratbag.git
cd libratbag
meson builddir --prefix=/usr/
```
I get:
```
~/libratbag$ meson builddir --prefix=/usr/
The Meson build system
Version: 0.45.1
Source dir: /home/dgroos/libratbag
Build dir: /home/dgroos/libratbag/builddir
Build type: native build
Project name: libratbag
Native C compiler: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Native C++ compiler: c++ (gcc 7.3.0 "c++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Found Pkg-config: NO

meson.build:50:0: ERROR: Pkg-config not found.

A full log can be found at /home/dgroos/libratbag/builddir/meson-logs/meson-log.txt
```
Neither checking out the logs nor googling "meson.build:50:0: ERROR: Pkg-config not found" provided me with a direction useful to me. Am I asking for support in the wrong quarters?

**Comment by FFY00** [comment]
It did provide useful information. You are missing `pkg-config`

Please do the following.
```
sudo apt install pkg-config
```

**Comment by dgroos** [comment]
This worked and thanks for the advice on searching application-specific error messages.
After successfully installing pkg-config I continued the process of installing all of the dependencies, 1 at a time (literally some 25 other packages!). Finally I got glib-2.0 to work and successfully ran: meson builddir --prefix=/usr/

I rebooted and tried: sudo ratbagd but it returned:  sudo: ratbagd: command not found
(Also, I saw there was an issue on my install of ubuntu 18.04 with glib-2.0 but sent in an auto error report but that's probably not connected to me being unable to find the ratbagd command). Any ideas?

**Comment by Hjdskes** [comment]
Did you actually compile and install the compiled files? After running meson, you need to first compile with `ninja -C builddir` and then install with `ninja -C builddir install`.

**Comment by dgroos** [comment]
I see, I misunderstood the directions (due to limited experience). So, I did what you said and went through the rest of the directions and got ratbagd.service running, Thanks! 

I then installed piper. I then launched piper by clicking on the icon. It didn't work then after a bit it issued a crash report containing lots of info. Here's seemingly most important:
> Title: "piper crashed with ModuleNotFoundError in_main_:No module named 'piper'"
> The traceback said:
> File "/usr/bin/piper",line 36, in <module>
> from piper.application import Application
> ModuleNotFoundError: No module name 'piper'
> And then it says the UnreportableReason is: "This package does not seem to be installed correctly"

So it looks like even though piper installation seemed to complete successfully, it didn't. Any ideas?

**Comment by FFY00** [comment]
If you run it again, the behavior is the same or does it not start at all?

**Comment by FFY00** [comment]
Show the output of `python --version`.

**Comment by dgroos** [comment]
python --version
Python 2.7.15rc1
But by typing in python3 -V I get Python 3.6.5.
I guess I need to make python 3 default. Will I have to reinstall things related to libratbag and piper?
Thanks again.

**Comment by FFY00** [comment]
No, that shouldn't be the problem as piper specifies python 3 as the environment. There was no need to check the version, sorry. That is probably a bad installation.

**Comment by dgroos** [comment]
np. Are you saying I should try to reinstall piper?

**Comment by FFY00** [comment]
Yeah, you should try.

**Comment by dgroos** [comment]
Since it wouldn't overwrite it, I removed builddir
`sudo rm -r piper/builddir`
Then ran
`meson builddir --prefix=/usr/`
giving this output:
> meson builddir --prefix=/usr/
> The Meson build system
> Version: 0.45.1
> Source dir: /home/myuser/piper
> Build dir: /home/myuser/piper/builddir
> Build type: native build
> WARNING: Newline character in a string detected, use ''' (three single quotes) for multiline strings instead.
> This will become a hard error in a future Meson release. config_piper_devel.set('devel', ' 43 32
> Project name: piper
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Found pkg-config: /usr/bin/pkg-config (0.29.1)
> Native dependency python3 found: YES 3.6
> Native dependency pygobject-3.0 found: YES 3.26.1
> Configuring AboutDialog.ui using configuration
> Native dependency glib-2.0 found: YES 2.56.1
> Message: Getting Python3 install dir
> Configuring piper using configuration
> Configuring piper.devel using configuration
> Program meson_install.sh found: YES (/usr/bin/env sh /home/myuser/piper/meson_install.sh)
> Build targets in project: 4
> Found ninja-1.8.2 at /usr/bin/ninja

From there I tried to start piper by clicking on the icon of the application and it showed it tried to open for 5-10 seconds then the booting application icon was gone. Here's the output of /var/log/syslog:

> Apr 22 14:31:20 myputer org.freedesktop.Piper.desktop[3583]: Traceback (most recent call last):
> Apr 22 14:31:20 myputer org.freedesktop.Piper.desktop[3583]:   File "/usr/bin/piper", line 36, in <module>
> Apr 22 14:31:20 myputer org.freedesktop.Piper.desktop[3583]:     from piper.application import Application
> Apr 22 14:31:20 myputer org.freedesktop.Piper.desktop[3583]: ModuleNotFoundError: No module named 'piper'

Ideas?

**Comment by dgroos** [comment]
I'm thinking I ought to move that last post to the piper bugs list--yes?

**Comment by FFY00** [comment]
Did you run this?

```
ninja -C builddir
sudo ninja -C builddir install
```

**Comment by dgroos** [comment]
aarg! I checked and saw I didn't so therefore repeated the steps:
`myuser@myputer:~/piper$ sudo rm -r builddir/`
`myuser@myputer:~/piper$ meson builddir --prefix=/usr/`

> The Meson build system
> Version: 0.45.1
> Source dir: /home/myuser/piper
> Build dir: /home/myuser/piper/builddir
> Build type: native build
> WARNING: Newline character in a string detected, use ''' (three single quotes) for multiline strings instead.
> This will become a hard error in a future Meson release. config_piper_devel.set('devel', ' 43 32
> Project name: piper
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Found pkg-config: /usr/bin/pkg-config (0.29.1)
> Native dependency python3 found: YES 3.6
> Native dependency pygobject-3.0 found: YES 3.26.1
> Configuring AboutDialog.ui using configuration
> Native dependency glib-2.0 found: YES 2.56.1
> Message: Getting Python3 install dir
> Configuring piper using configuration
> Configuring piper.devel using configuration
> Program meson_install.sh found: YES (/usr/bin/env sh /home/myuser/piper/meson_install.sh)
> Build targets in project: 4
> Found ninja-1.8.2 at /usr/bin/ninja

`myuser@myputer:~/piper$ ninja -C builddir`

> ninja: Entering directory `builddir'
> [1/1] Generating piper_gresource with a custom command.

`myuser@myputer:~/piper$ sudo ninja -C builddir install`

> ninja: Entering directory `builddir'
> [0/1] Installing files.
> Installing subdir /home/myuser/piper/piper to /usr/lib/python3.6/site-packages/piper
> Installing data/piper.gresource to /usr/share/piper/piper.gresource
> Installing /home/myuser/piper/data/org.freedesktop.Piper.desktop to /usr/share/applications
> Installing /home/myuser/piper/data/org.freedesktop.Piper.svg to /usr/share/icons/hicolor/scalable/apps
> Installing /home/myuser/piper/builddir/piper to /usr/bin
> Running custom install script '/usr/bin/python3 /usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=piper'
> Installing /home/myuser/piper/builddir/po/de.gmo to /usr/share/locale/de/LC_MESSAGES/piper.mo
> Installing /home/myuser/piper/builddir/po/hr.gmo to /usr/share/locale/hr/LC_MESSAGES/piper.mo
> Installing /home/myuser/piper/builddir/po/nl.gmo to /usr/share/locale/nl/LC_MESSAGES/piper.mo
> Installing /home/myuser/piper/builddir/po/pl.gmo to /usr/share/locale/pl/LC_MESSAGES/piper.mo
> Installing /home/myuser/piper/builddir/po/sv.gmo to /usr/share/locale/sv/LC_MESSAGES/piper.mo
> Running custom install script '/usr/bin/env sh /home/myuser/piper/meson_install.sh'
> gtk-update-icon-cache: Cache file created successfully.

Still doesn't work :-(
syslog shows:

> Apr 22 15:30:38 myputer org.freedesktop.Piper.desktop[4215]: Traceback (most recent call last):
> Apr 22 15:30:38 myputer org.freedesktop.Piper.desktop[4215]:   File "/usr/bin/piper", line 36, in <module>
> Apr 22 15:30:38 myputer org.freedesktop.Piper.desktop[4215]:     from piper.application import Application
> Apr 22 15:30:38 myputer org.freedesktop.Piper.desktop[4215]: ModuleNotFoundError: No module named 'piper'

**Comment by FFY00** [comment]
That's weird. Maybe @Hjdskes could help? At this point, I think you should open an issue in the piper repository.

**Comment by dgroos** [comment]
Thanks for your efforts to help me @FFY00 !
Will open issue in piper repository.

**Comment by FFY00** [comment]
No problem! You can close this issue now.
