### ISSUE TITLE
Compile error - UnicodeDecodeError on tools/merge_ratbagd.py

### ISSUE THREAD

**Issue by guiambros** [libratbag/libratbag#493]
I'm trying to compile libratbag on Ubuntu 18.04,Python 3.6.5, but kept getting UnicodeDecodeError errors on `merge_bagratd.py`.

```
$ python3 -V
Python 3.6.5

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic

$ meson builddir --prefix=/usr/ -Dsystemd-unit-dir=/lib/systemd/system
The Meson build system
Version: 0.45.1
Source dir: /repo/mouse-keys/libratbag
Build dir: /repo/mouse-keys/libratbag/builddir
Build type: native build
Project name: libratbag
Native C compiler: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Native C++ compiler: c++ (gcc 7.3.0 "c++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libudev found: YES 237
Native dependency libevdev found: YES 1.5.9
Native dependency libsystemd found: YES 237
Native dependency systemd found: YES 237
Native dependency glib-2.0 found: YES 2.56.1
Library m found: YES
Configuring libratbag-version.h using configuration
Configuring lur-command.1 using configuration
Program /repo/mouse-keys/libratbag/data/devices/data-parse-test.py found: YES (/repo/mouse-keys/libratbag/data/devices/data-parse-test.py)
Program data/gnome/check-svg.py found: YES (/repo/mouse-keys/libratbag/data/gnome/check-svg.py)
Native dependency check found: YES 0.10.0
Program valgrind found: YES (/usr/bin/valgrind)
Configuring org.freedesktop.ratbag_devel1.conf using configuration
Configuring ratbagd.service using configuration
Configuring org.freedesktop.ratbag1.service using configuration
Configuring org.freedesktop.ratbag1.conf using configuration
Configuring ratbagctl.1 using configuration
Configuring ratbagctl.devel using configuration
Configuring ratbagctl.test using configuration
Program /repo/mouse-keys/libratbag/builddir/ratbagctl.test found: YES (/repo/mouse-keys/libratbag/builddir/ratbagctl.test)
Configuring toolbox.py using configuration
Configuring config.h using configuration
Program swig found: YES (/usr/bin/swig)
Native dependency python3 found: YES 3.6
Build targets in project: 22
Found ninja-1.8.2 at /usr/bin/ninja

$ ninja -C builddir
ninja: Entering directory `builddir'
[69/73] Generating ratbagctl with a custom command.
FAILED: ratbagctl
/usr/bin/python3 /repo/mouse-keys/libratbag/tools/merge_ratbagd.py ../tools/ratbagctl.in ../tools/ratbagd.py --output ratbagctl --version 0.9.902
Traceback (most recent call last):
  File "/repo/mouse-keys/libratbag/tools/merge_ratbagd.py", line 67, in <module>
    main(sys.argv[1:])
  File "/repo/mouse-keys/libratbag/tools/merge_ratbagd.py", line 60, in main
    print_ratbagctl(ns.ratbagctl, ns.ratbagd, ns.version)
  File "/repo/mouse-keys/libratbag/tools/merge_ratbagd.py", line 37, in print_ratbagctl
    for r in ratbagd.readlines():
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4851: ordinal not in range(128)
[70/73] Generating ratbag-command with a custom command.
FAILED: ratbag-command
/usr/bin/python3 /repo/mouse-keys/libratbag/tools/merge_ratbagd.py ../tools/ratbagctl.in ../tools/ratbagc.py --output ratbag-command --version 0.9.902
Traceback (most recent call last):
  File "/repo/mouse-keys/libratbag/tools/merge_ratbagd.py", line 67, in <module>
    main(sys.argv[1:])
  File "/repo/mouse-keys/libratbag/tools/merge_ratbagd.py", line 60, in main
    print_ratbagctl(ns.ratbagctl, ns.ratbagd, ns.version)
  File "/repo/mouse-keys/libratbag/tools/merge_ratbagd.py", line 37, in print_ratbagctl
    for r in ratbagd.readlines():
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7317: ordinal not in range(128)
[71/73] Generating 'libratbag@sha/libratbag.c'.
ninja: build stopped: subcommand failed.
```

I was able to trace it down to unicode characters used in `ratbagd.py`, specifically lines 813/815/819 (respectively ↓, ↑, ↕). 

>             "↓{}".format(ecodes.KEY[key][RatbagdMacro._PREFIX_LEN:]),
>        RatbagdButton.MACRO_KEY_RELEASE: lambda key:
>             "↑{}".format(ecodes.KEY[key][RatbagdMacro._PREFIX_LEN:]),
>        RatbagdButton.MACRO_WAIT: lambda val:
>             "{}ms".format(val),
>        _MACRO_KEY: lambda key:
>             "↕{}".format(ecodes.KEY[key][RatbagdMacro._PREFIX_LEN:]),

Took me a while to figure out, but I was finally able to fix and compile by making the following changes to `tools/merge_ratbagd.py`:

```
31d30
<
33c32
<     with open(ratbagctl_path, 'r') as ratbagctl, open(ratbagd_path, 'r') as ratbagd:
---
>     with open(ratbagctl_path, 'r', encoding='utf-8') as ratbagctl, open(ratbagd_path, 'r', encoding='utf-8') as ratbagd:
41c40,41
<                         print(r.rstrip('\n'))
---
>                         r = r.rstrip('\n').encode('utf-8')
>                         print(r)

```
At first I wasn't sure if this was something specific to my installation, but I was able to reproduce the issue on a docker container using 16.04. But strangely, these unicode characters were introduced by commit 39762718b94b11816a8191626a1c636166e6ad4c from September last year, so it's unusual that no one noticed it.

I can send a PR, if you think this is impacting others, and this is the right fix. Thanks!

**Comment by FFY00** [comment]
Okay, we would be happy to receive a PR from you.

**Comment by guiambros** [comment]
Thanks!
