### ISSUE TITLE
Microsoft Classic Intellimouse support

### ISSUE THREAD

**Issue by madsl** [libratbag/libratbag#537]
Microsoft recently did _another_ rerelease of the classic IntelliMouse Explorer 3.0 in June this year. This mouse has an adjustable DPI setting that you can set in Mouse and Keyboard Center 10 in Windows 10. It would be very nice if it were possible to adjust this DPI the same way in Linux.

What info is needed for this?

The mouse: https://www.microsoft.com/accessories/en-us/products/mice/microsoft-classic-intellimouse

**Comment by whot** [comment]
Simply said, someone needs to reverse-engineer the protocol and figure out how to talk to the mouse. Or alternatively get Microsoft to provide us with the protocol specifications :)

**Comment by madsl** [comment]
I made a rough capture - my mouse was already set to 800 DPI. I then went into Mouse and Keyboard center and dragged the DPI slider to the maximum (3200) and to the minimum (400) and every point in between (200 DPI between each point for a totalt of 15 points). Some back and forth movements of the slider too...
[intellimouseclassic.pcapng.gz](https://github.com/libratbag/libratbag/files/2419396/intellimouseclassic.pcapng.gz)

**Comment by madsl** [comment]
You also have the possibility to remap the keys and record macros in Mouse and Keyboard Center, but I guess that might be unnecessary to make a packet capture for that..? (Isn't stuff like that most likely implemented on the driver side...?)

**Comment by HughPH** [comment]
Yeah remapping and macros are usually dealt with in software. As an architect I'd like to envisage a future where the functionality of libratrag or something similar is extended such that it forms a standard underlying layer and the major desktop environments each have an extended mouse configuration page.

**Comment by vanillajonathan** [comment]
@madsl The USB device identifier is needed. You can get it by running `lsusb`.

**Comment by madsl** [comment]
@vanillajonathan 
Bus 001 Device 008: ID 045e:0823 Microsoft Corp.

**Comment by vanillajonathan** [comment]
With this you could try create a .device file. There is an example file here.
https://github.com/libratbag/libratbag/blob/master/data/devices/device.example

Filename: `microsoft-intellimouse-classic-2018.device`

It would look something like this:
```ini
[Device]
Name=Microsoft Classic Intellimouse
DeviceMatch=usb:045e:0823
```

**Comment by bentiss** [comment]
An other note. According to the wireshark capture, the device has 2 HID interfaces. The one @whot mentioned and an other one that contains the feature reports to configure it (enumeration happens at lines 1205 and 1210):

```
0x05, 0x0c,                    // Usage Page (Consumer Devices)       0
0x09, 0x01,                    // Usage (Consumer Control)            2
0xa1, 0x01,                    // Collection (Application)            4
0x85, 0x1c,                    //  Report ID (28)                     6
0x06, 0x00, 0xff,              //  Usage Page (Vendor Defined Page 1) 8
0x0a, 0x22, 0xff,              //  Usage (Vendor Usage 0xff22)        11
0x15, 0x00,                    //  Logical Minimum (0)                14
0x25, 0x04,                    //  Logical Maximum (4)                16
0x75, 0x08,                    //  Report Size (8)                    18
0x95, 0x01,                    //  Report Count (1)                   20
0x81, 0x02,                    //  Input (Data,Var,Abs)               22
0x0a, 0x25, 0xff,              //  Usage (Vendor Usage 0xff25)        24
0x15, 0x00,                    //  Logical Minimum (0)                27
0x25, 0x04,                    //  Logical Maximum (4)                29
0x75, 0x08,                    //  Report Size (8)                    31
0x95, 0x01,                    //  Report Count (1)                   33
0x81, 0x02,                    //  Input (Data,Var,Abs)               35
0x0a, 0x26, 0xff,              //  Usage (Vendor Usage 0xff26)        37
0x15, 0x00,                    //  Logical Minimum (0)                40
0x27, 0xff, 0xff, 0x00, 0x00,  //  Logical Maximum (65535)            42
0x75, 0x10,                    //  Report Size (16)                   47
0x95, 0x01,                    //  Report Count (1)                   49
0x81, 0x02,                    //  Input (Data,Var,Abs)               51
0x85, 0x24,                    //  Report ID (36)                     53
0x06, 0x00, 0xff,              //  Usage Page (Vendor Defined Page 1) 55
0x0a, 0x0a, 0xfa,              //  Usage (Vendor Usage 0xfa0a)        58
0x15, 0x00,                    //  Logical Minimum (0)                61
0x26, 0xff, 0x00,              //  Logical Maximum (255)              63
0x75, 0x08,                    //  Report Size (8)                    66
0x95, 0x1f,                    //  Report Count (31)                  68
0xb1, 0x02,                    //  Feature (Data,Var,Abs)             70
0x85, 0x27,                    //  Report ID (39)                     72
0x06, 0x00, 0xff,              //  Usage Page (Vendor Defined Page 1) 74
0x0a, 0x0a, 0xfa,              //  Usage (Vendor Usage 0xfa0a)        77
0x81, 0x02,                    //  Input (Data,Var,Abs)               80
0x85, 0x2a,                    //  Report ID (42)                     82
0x06, 0x00, 0xff,              //  Usage Page (Vendor Defined Page 1) 84
0x0a, 0x0a, 0xfa,              //  Usage (Vendor Usage 0xfa0a)        87
0x95, 0x08,                    //  Report Count (8)                   90
0x81, 0x02,                    //  Input (Data,Var,Abs)               92
0xc0,                          // End Collection                      94
```

There seem to be also 1 more USB endpoints as we are seeing events from the 1.8.3 device.

In the capture, I can see that there are a bunch of `SET_REPORT` and `GET_REPORT` on report IDs `36` and `39`.
- The very first are sending some ascii data to the mouse (`Y.B.O.A.R.D.` and `ic IntelliMouse` are in plain text)
- then we have others that send raw data of a yet to be discovered protocol

From what I can see, the protocol is not trivial. You'll need to analyze it by interacting with the UI to get the mapping between one DPI change and which reports are sent to the device.

**Comment by rpavlik** [comment]
So not sure my odds, but I do have contacts at MS that I might be able to network thru to get to the hardware division for protocol info. If nothing else, I've had experience reversing USB before, and I now have one of these mice, so interested in helping. I like the buttery-smoothness, but a little higher speed would be a worthwhile tradeoff :)

**Comment by FFY00** [comment]
Yes, that would be great. If you can get them to share some documentation we can add support.

**Comment by rpavlik** [comment]
No guarantees - I'll put it on my list for after they find the answer to the current question I've posed to them :)

**Comment by FFY00** [comment]
Sure, thank you :)

**Comment by K-Visscher** [comment]
I've got a Pro IntelliMouse (045E:082A) and I reverse engineered (partially) the used protocol, it's quite simple but has some quirks. 

If we take a look at the capture of @madsl, the Pro IntelliMouse and Classic IntelliMouse, at first glance seem very similiar. 

- [Here's](https://i.imgur.com/cOsP98a.png) a screen capture of Pro being set to 16000 DPI   
   (notice the 0x80, 0x3E corresponing in little endian to 16000)
- [here's](https://i.imgur.com/109g8Wj.png) one of the Classic being set to 1600 DPI 
   (notice the 0x00, 0x40, 0x06 corresponing in little endian to 1600)

So basically with both, you send a SET_REPORT for REPORT_ID 0x24.

Classic IntelliMouse
```
ReportID,PropertyID,Length,Data
[0x24],[0x96],[0x03],[0x00, 0x40, 0x06]
```

Pro IntelliMouse
```
ReportID,PropertyID,Length,Data
[0x24],[0x96],[0x02],[0x80, 0x3E]
```
Where the property id is the property you want to change, in this case 0x96 corresponds to DPI.
After the data part you can just pad it with `0x00`'s until the total size matches the report count.
The Pro has a different report count (72) than the Classic (32) 

I've also made a [gist](https://gist.github.com/K-Visscher/22561ca69a64339a7383d67db6e79818) to test my theory, if somebody with a Classic IntelliMouse would be willing to try it out and tell me if it works, that would be great.

For the Pro IntelliMouse see this [source file](https://github.com/K-Visscher/Pro-IntelliMouse-Control-Panel/blob/master/src/main/python/intellimouse.py)

**Comment by madsl** [comment]
Omg awesome! I have both, I'll test as soon as I get home.

**Comment by madsl** [comment]
I'm not able to get rid of "Resource busy" when trying intellimouse.py with a Pro IntelliMouse (tried on the terminal with no X running too):

> $ sudo python -c 'import intellimouse; intellimouse.IntelliMouse()'
Password: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mads/kode/intellimouse.py", line 34, in __init__
    self.device.set_configuration()
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 869, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 148, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 794, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy

**Comment by FFY00** [comment]
If you are using hidapi with the libusb backend in `intellimouse.py`, I think libusb by default tries to claim the device which probably can't happen since we are using it. Use hidapi with the hidraw backend instead.

**Comment by K-Visscher** [comment]
> I'm not able to get rid of "Resource busy" when trying intellimouse.py with a Pro IntelliMouse (tried on the terminal with no X running too):
> 
> > $ sudo python -c 'import intellimouse; intellimouse.IntelliMouse()'
> > Password:
> > Traceback (most recent call last):
> > File "", line 1, in 
> > File "/home/mads/kode/intellimouse.py", line 34, in **init**
> > self.device.set_configuration()
> > File "/usr/lib/python3.7/site-packages/usb/core.py", line 869, in set_configuration
> > self._ctx.managed_set_configuration(self, configuration)
> > File "/usr/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
> > return f(self, *args, **kwargs)
> > File "/usr/lib/python3.7/site-packages/usb/core.py", line 148, in managed_set_configuration
> > self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
> > File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 794, in set_configuration
> > _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
> > File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
> > raise USBError(_strerror(ret), ret, _libusb_errno[ret])
> > usb.core.USBError: [Errno 16] Resource busy

@madsl please try again, with `sudo python3`, it should be "fixed" now.. Note you won't be able to use your mouse while configuring (so have a spare one handy). 
@FFY00 yeah, using hidapi would probably be better and easier, but this is fine for my use case 🤷

**Comment by madsl** [comment]
@K-Visscher nice, it worked!
>$ sudo ipython
Password: 
Python 3.7.7 (default, May  8 2020, 21:56:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.
>In [1]: import intellimouse                                                                                                                                                                  
>In [2]: m = intellimouse.IntelliMouse()                                                                                                                                                      
>In [3]: m.device                                                                                                                                                                             
>Out[3]: <DEVICE ID 045e:082a on Bus 001 Address 004>
>In [4]: m.get_color()                                                                                                                                                                        
>Out[4]: 16712705
In [5]: m.get_polling_rate                                                                                                                                                                   
Out[5]: <bound method IntelliMouse.get_polling_rate of <intellimouse.IntelliMouse object at 0x7f732b7d9e90>>
In [6]: m.get_polling_rate()                                                                                                                                                                 
Out[6]: 1000
In [7]:                                                                                                                                                                                      
In [7]: m.get_dpi()                                                                                                                                                                          
Out[7]: 1600
In [8]: m.set_dpi(2000)                                                                                                                                                                      
In [9]: m.get_dpi()                                                                                                                                                                          
Out[9]: 2000
In [10]:                                                                                                                                                                                     
Do you really want to exit ([y]/n)? 
libusb: error [seek_to_next_config] descriptor is not a config desc (type 0x00)
Segmentation fault

**Comment by K-Visscher** [comment]
> @K-Visscher nice, it worked!
> 
> > $ sudo ipython
> > Password:
> > Python 3.7.7 (default, May  8 2020, 21:56:26)
> > Type 'copyright', 'credits' or 'license' for more information
> > IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.
> > In [1]: import intellimouse
> > In [2]: m = intellimouse.IntelliMouse()
> > In [3]: m.device
> > Out[3]: <DEVICE ID 045e:082a on Bus 001 Address 004>
> > In [4]: m.get_color()
> > Out[4]: 16712705
> > In [5]: m.get_polling_rate
> > Out[5]: <bound method IntelliMouse.get_polling_rate of <intellimouse.IntelliMouse object at 0x7f732b7d9e90>>
> > In [6]: m.get_polling_rate()
> > Out[6]: 1000
> > In [7]:
> > In [7]: m.get_dpi()
> > Out[7]: 1600
> > In [8]: m.set_dpi(2000)
> > In [9]: m.get_dpi()
> > Out[9]: 2000
> > In [10]:
> > Do you really want to exit ([y]/n)?
> > libusb: error [seek_to_next_config] descriptor is not a config desc (type 0x00)
> > Segmentation fault

To get rid of that nasty looking segfault exit using `exit()`, or let the mouse IntelliMoise object go out of scope like so `m = None`

**Comment by madsl** [comment]
@K-Visscher It worked setting DPI on the Classic after adding your [reattach patch](https://github.com/K-Visscher/Pro-IntelliMouse-Control-Panel/commit/30f8f5fbefa71220bdcee62a0b5d74c9b2d277b0) to your gist :)

>$ sudo ipython
Python 3.7.7 (default, May  8 2020, 21:56:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.
>
>In [1]: from intellimouse_classic import IntelliMouse                                                                                                                                        
>
>In [2]: m = IntelliMouse()                                                                                                                                                                   
>
>In [3]: m.set_dpi(400)                                                                                                                                                                       
>
>In [4]: exit                                                                                                                                                                                 
libusb: error [seek_to_next_config] descriptor is not a config desc (type 0x8f)
Segmentation fault

After doing this, the DPI was set to 400 :)

**Comment by vanillajonathan** [comment]
@madsl & @k-visscher You who have experience with these devices, perhaps you could get them working with libratbag?

**Comment by okkiv** [comment]
I'm looking through the sources at the moment and will try to add support for the classic and pro

**Comment by MLSci** [comment]
> 
I also have a Microsoft 5050 mouse that has left and right side button, which can be programmed as keyboard shortcut in Microsoft Keyboard and Mouse Center. It'll be nice to be able to use it in Linux too. I'm not familiar with how it can be implemented, but let me know if there's anything I can do from my end. 

Keep it up :)

**Comment by daemonspudguy** [comment]
So @okkiv has made a fork for this but it appears that it was never made into a PR.
