### ISSUE TITLE
Support for logitech-M510

### ISSUE THREAD

**Issue by arian81** [libratbag/libratbag#714]
Please add support for logitech-m510 mouses if possible

**Comment by whot** [comment]
Have you tried adding a .device file for the M510? Might be that libratbag already supports it, it just needs to be enabled. Have a look at the .device files in your system, then copy+modify one so it matches the USB ID of the M510, this should usually work.

**Comment by herculesgabriel** [comment]
> Have you tried adding a .device file for the M510? Might be that libratbag already supports it, it just needs to be enabled. Have a look at the .device files in your system, then copy+modify one so it matches the USB ID of the M510, this should usually work.

How can I do that?

**Comment by whot** [comment]
https://github.com/libratbag/libratbag/wiki/Adding-a-device

**Comment by herculesgabriel** [comment]
> https://github.com/libratbag/libratbag/wiki/Adding-a-device

I'm sorry, but I'm having trouble doing this. What is the name of the file I should put in the location and what am I supposed to change?

**Comment by herculesgabriel** [comment]
> https://github.com/libratbag/libratbag/wiki/Adding-a-device

I'm getting this:

```
sudo ratbagctl list
Traceback (most recent call last):
  File "/usr/bin/ratbagctl", line 34, in <module>
    from ratbagd import *
  File "/usr/share/ratbagd/ratbagd/__init__.py", line 26, in <module>
    from gi.repository import GLib
ImportError: No module named gi.repository
```
I put a m510.device file with this code inside:

```
# Logitech G900
[Device]
Name=Logitech G900
DeviceMatch=usb:046d:c52b;
Driver=hidpp20
```
This "046d:c52b" is my device. What should I do?

**Comment by FFY00** [comment]
You are missing a dependency, how did you install libratbag?

`c52b` is not your device, it's the receiver. Make sue you are running at least Linux 5.2 and run `ratbagd --verbose=raw`. There you should see a device with an ID starting in 4, that's your device.

**Comment by herculesgabriel** [comment]
I'm using Deepin 15.11. I installed "ratbagd" using a "apt install" cmd and "Piper" via flathub package. Then I put the ".device" file here:

![DeepinScreenshot_dde-desktop_20190804114143](https://user-images.githubusercontent.com/51159478/62425039-028e7a00-b6ad-11e9-8895-7ca4d47f004f.png)
![DeepinScreenshot_dde-desktop_20190804114135](https://user-images.githubusercontent.com/51159478/62425041-06220100-b6ad-11e9-901a-524fb610668d.png)

The code you sent:

```
~$ sudo ratbagd --verbose=raw
Usage: ratbagd [--verbose]
ratbagd error: Failed: Invalid argument
~$ sudo ratbagd --verbose
ratbag debug: Logitech M510 is device '/dev/hidraw3'.
ratbag debug: report ID 02
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: report ID 20
ratbag debug: report ID 21
ratbag debug: 'Logitech M510' is using protocol v4.5
ratbag debug: device battery level is 70% (next 5%), status 0 
ratbag debug: device has programmable keys/buttons
ratbag debug: driver match found: Logitech HID++2.0
event9: "Logitech M510", 1 profiles
```
lsusb:

```
~$ lsusb
Bus 002 Device 004: ID 258a:1006  
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 004: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 003: ID 04f2:b351 Chicony Electronics Co., Ltd 
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by FFY00** [comment]
Looks like you're in libratbag 0.9 which is incredible outdated. Please update it. You could add [this ppa](https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git) or build the project from source.

**Comment by herculesgabriel** [comment]
> Looks like you're in libratbag 0.9 which is incredible outdated. Please update it. You could add [this ppa](https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git) or build the project from source.

Yeah, I just realized that. It's because Deepin is using Debian 9 instead of 10. 
![DeepinScreenshot_select-area_20190804143624](https://user-images.githubusercontent.com/51159478/62427176-615fed80-b6c5-11e9-995d-53d7ffa4d60e.png)
![DeepinScreenshot_select-area_20190804143616](https://user-images.githubusercontent.com/51159478/62427178-645ade00-b6c5-11e9-9ee2-a0dcfc5898f6.png)
Things will get more complicated because of this. I can't just install since there are other dependences broken. I'll see what I can do to solve that, but thank you for your help!

**Comment by FFY00** [comment]
Can we get an update on this? Did you manage to get it working?

**Comment by arian81** [comment]
To be honest like I started the question but I got so busy I forgot about
the whole thing but others continued the thread and they may be able to
help you

**Comment by herculesgabriel** [comment]
> Can we get an update on this? Did you manage to get it working?

I'm still using Deepin, so I decided to just forget about that since everything will be complicated to solve, but I think that for those who install the latest tools it'll be easy to add support manually.

**Comment by gunwald** [comment]
I tried to add support for the device, but could not make it work. This is my device file:

```
# Logitech M510
[Device]
Name=Logitech M510
DeviceMatch=usb:046d:1025;046a:0023
Driver=hidpp10
LedTypes=dpi

[Driver/hidpp10]
Profiles=5
ProfileType=G9
DpiList=200;400;600;800;1000;1200;1400;1600;1800;2000;2200;2400;2600;2800;3000;3200

Leds=1

```
rabag gives me this:

```
sudo ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: Logitech M510
ratbag debug: Using data directory '/usr/share/libratbag'
200;400;600;800;1000;1200;1400;1600;1800;2000;2200;2400;2600;2800;3000;3200: ratbag debug: device assigned driver hidpp10
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x1025
ratbag debug: Logitech M510 is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: - HID report ID 20
ratbag debug: - HID report ID 21
ratbag raw: Fetching individual features (0x1)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 01 | 00 00 00
ratbag raw: hidpp write:  10 00 81 01 00 00 00
ratbag raw: hidpp read:   10 01 81 01 82 00 00
ratbag raw: hidpp10 rx:  10 | 00 | 81 | 01 | 82 00 00
ratbag raw: Fetching HID++ notifications (00)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 00 | 00 00 00
ratbag raw: hidpp write:  10 00 81 00 00 00 00
ratbag raw: hidpp read:   10 01 81 00 10 00 00
ratbag raw: hidpp10 rx:  10 | 00 | 81 | 00 | 10 00 00
ratbag raw: Fetching current resolution (0x63)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 63 | 00 00 00
ratbag raw: hidpp write:  10 00 81 63 00 00 00
ratbag raw: hidpp read:   10 01 8f 81 63 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 63 02 00
ratbag raw: Fetching LED status (0x51)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 51 | 00 00 00
ratbag raw: hidpp write:  10 00 81 51 00 00 00
ratbag raw: hidpp read:   10 01 8f 81 51 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 51 02 00
ratbag raw: Fetching USB refresh rate (0x64)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 64 | 00 00 00
ratbag raw: hidpp write:  10 00 81 64 00 00 00
ratbag raw: hidpp read:   10 01 8f 81 64 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 64 02 00
ratbag raw: Fetching optical sensor settings (0x61)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 61 | 00 00 00
ratbag raw: hidpp write:  10 00 81 61 00 00 00
ratbag raw: hidpp read:   10 01 8f 81 61 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 61 02 00
ratbag raw: Fetching current profile (0xf)
ratbag raw: hidpp10 tx:  10 | 00 | 81 | 0f | 00 00 00
ratbag raw: hidpp write:  10 00 81 0f 00 00 00
ratbag raw: hidpp read:   10 01 8f 81 0f 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw: hidpp10 rx:  10 | 00 | 8f | 81 | 0f 02 00
ratbag error: Failed to get HID++1.0 device for Logitech M510
ratbag error: Logitech M510: error opening hidraw node (Unknown error -2)
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046d:c52b
ratbag debug: New device: HID 046a:0023
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046a:0023
ratbag debug: New device: HID 046a:0023
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 046a:0023
DBus server ready

```

Franky I don't now nothing about the technical background of pointer devices on Linux, so I am lost here.

**Comment by gunwald** [comment]
Couple of days ago, my beloved but old mouse (Logitech M510, 2013 model) sadly died (I think it was his hard). To overcome this rotten feeling I just got a brand new one. He looks exactly like the old one (Logitech M510 5099206022126) but inside he seems to have much better guts. So I got him to work together with `libratbag` with this config:
```
# Logitech M510
[Device]
Name=Logitech M510
DeviceMatch=usb:046d:4051
Driver=hidpp20

```
![2021-04-28_13-00](https://user-images.githubusercontent.com/1161825/116393513-04558500-a822-11eb-9bd6-0a06c201be2b.png)

But unfortunately I could map any action other than the predefined clicks to any mouse key with piper. Trying to do so, by appointing a key combination I get in error message:

![2021-04-28_13-06](https://user-images.githubusercontent.com/1161825/116394009-a5dcd680-a822-11eb-9d20-532226e27b96.png)

Is there any way to configure such a mapping directly in the libratbag config?

**Comment by jonatandevbr** [comment]
> Couple of days ago, my beloved but old mouse (Logitech M510, 2013 model) sadly died (I think it was his hard). To overcome this rotten feeling I just got a brand new one. He looks exactly like the old one (Logitech M510 5099206022126) but inside he seems to have much better guts. So I got him to work together with `libratbag` with this config:
> 
> ```
> # Logitech M510
> [Device]
> Name=Logitech M510
> DeviceMatch=usb:046d:4051
> Driver=hidpp20
> ```
> 
> ![2021-04-28_13-00](https://user-images.githubusercontent.com/1161825/116393513-04558500-a822-11eb-9bd6-0a06c201be2b.png)
> 
> But unfortunately I could map any action other than the predefined clicks to any mouse key with piper. Trying to do so, by appointing a key combination I get in error message:
> 
> ![2021-04-28_13-06](https://user-images.githubusercontent.com/1161825/116394009-a5dcd680-a822-11eb-9d20-532226e27b96.png)
> 
> Is there any way to configure such a mapping directly in the libratbag config?

Hi, I'm facing the same error! Did you manage to solve it somehow? Grateful!

**Comment by gunwald** [comment]
No, I gave up on this. But I manged to make the extra button work with https://github.com/sezanzeb/input-remapper.
