### ISSUE TITLE
Add Support for MX Vertical

### ISSUE THREAD

**Issue by Noh3choo** [libratbag/libratbag#719]
Can someone assist me with adding support for the MX Vertical? I have tried the following

```
~/Downloads/libratbag/builddir$ cat ../data/devices/logitech-MX-Vertical.device 
# Logitech MX Vertical
[Device]
Name=Logitech MX Vertical 
DeviceMatch=usb:046d:407b
Driver=hidpp20
```

However
```
$ sudo ./ratbagctl -vvv list
No devices available.
```

But if I try `ratbagctl.devel` stuff starts to happen
```
$ sudo ./ratbagctl.devel list
thundering-hare:     Logitech MX Vertical            
bawling-hare:        Test device                     
```

More info:
```
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x407b
ratbag debug: Logitech MX Vertical is device '/dev/hidraw5'.
...
ratbag debug: 'Logitech MX Vertical' is using protocol v4.5
ratbag raw: 'Logitech MX Vertical' has 34 features
```

But I cant get the non development executable/running daemon to work with this mouse.

**Comment by FFY00** [comment]
How did you install this libratbag? If you installed via the git repo what prefix did you use?

Can' you post the output of `/usr/bin/ratbagd --version` and `/usr/local/bin/ratbagd --version`.

I think you might have installed multiple versions with different prefixes and the one in `/usr/local` is being used to resolve `$ ratbagd`.

**Comment by Noh3choo** [comment]
I have `libratbag` installed via Ubuntu 19.04 apt, after adding the device file to `/usr/share/libratbag/devices/logitech-MX-Vertical.device` and restarting the services it did not appear to be working so I tried the .devel binary from the latest release of this repository.

I restarted my PC today and it seems to be working, but I cant seem to get the set resolution working:

```
$which ratbagctl
/usr/local/bin/ratbagctl
$ratbagctl list
yapping-groundhog:   Logitech MX Vertical            
$sudo ratbagctl yapping-groundhog dpi set 4000
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/_propertyhelper.py", line 404, in obj_set_property
    prop.fset(self, value)
  File "/usr/local/bin/ratbagctl", line 570, in resolution
    self._set_dbus_property("Resolution", "v", variant)
  File "/usr/local/bin/ratbagctl", line 196, in _set_dbus_property
    2000, None)
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Incorrect parameters for property 'Resolution', expected '(uu)', got 'v'. (16)
$ratbagctl yapping-groundhog dpi set 4000
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/_propertyhelper.py", line 404, in obj_set_property
    prop.fset(self, value)
  File "/usr/local/bin/ratbagctl", line 570, in resolution
    self._set_dbus_property("Resolution", "v", variant)
  File "/usr/local/bin/ratbagctl", line 196, in _set_dbus_property
    2000, None)

```

**Comment by FFY00** [comment]
There is definitely a version mismatch here. You installed two versions, one via the package manager and other manually. Probably the daemon being run is `/usr/bin/ratbagd` which comes from the system package and you are executing `$ ratbagctl` which resolves to `/usr/local/bin/ratbagctl`. Please run `meson uninstall` in the libratbag folder you use to install or remove the system package.

**Comment by Noh3choo** [comment]
You are right, I purged all of the apt install and installed my compiled version and symlinked the files installed to `/usr/local/` to these paths:
```
/usr/share/dbus-1/system.d/org.freedesktop.ratbag1.conf
/usr/share/dbus-1/system-services/org.freedesktop.ratbag1.conf
/usr/share/systemd/system/ratbagd.service
```

So things are better now:
```
$sudo ratbagctl list
hooting-chinchilla:  Logitech MX Vertical            
$sudo ratbagctl hooting-chinchilla dpi set 4000
$sudo ratbagctl hooting-chinchilla dpi get 
4000dpi
$sudo ratbagctl hooting-chinchilla dpi set 400
$sudo ratbagctl hooting-chinchilla dpi get 
400dpi
```

So it appears to be working but the dpi setting seems to have no effect.

**Comment by Noh3choo** [comment]
```
$sudo ratbagctl hooting-chinchilla info
hooting-chinchilla - Logitech MX Vertical
 Number of Buttons: 7
    Number of Leds: 0
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Report Rate: 0Hz
  Resolutions:
    0: 400dpi (active)
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to UNKNOWN
  Button: 6 is mapped to UNKNOWN
```

**Comment by Noh3choo** [comment]
The mouse seems to save 2 profiles that are toggled with the top button, I can see this taking affect by invoking `ratbagd --verbose` after doing the toggle:

```
ratbagd --verbose
ratbag debug: New device: Logitech MX Vertical
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x407b
ratbag debug: Logitech MX Vertical is device '/dev/hidraw5'.
ratbag debug: HID report ID 01
ratbag debug: HID report ID 0e
ratbag debug: HID report ID 02
ratbag debug: HID report ID 03
ratbag debug: HID report ID 10
ratbag debug: HID report ID 11
ratbag debug: HID report ID 20
ratbag debug: HID report ID 21
ratbag debug: 'Logitech MX Vertical' is using protocol v4.5
ratbag debug: device battery level is 50% (next 20%), status 0 
ratbag debug: device has programmable keys/buttons
ratbag debug: device has 7 buttons
ratbag debug: device has adjustable dpi
ratbag debug: device is at 1600 dpi (variable between 400 and 4000).
ratbag debug: device is at 1600 dpi (variable between 400 and 4000).
ratbag debug: device has 7 buttons
ratbag debug: driver match found: Logitech HID++2.0
hidraw5: "Logitech MX Vertical", 1 profiles
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 046d:c52b
```

Switching the onboard mouse profile and trying again:

```
$sudo ratbagd --verbose
ratbag debug: New device: Logitech Logitech G930 Headset
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 046d:0a1f
ratbag debug: New device: Logitech MX Vertical
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x407b
ratbag debug: Logitech MX Vertical is device '/dev/hidraw5'.
ratbag debug: HID report ID 01
ratbag debug: HID report ID 0e
ratbag debug: HID report ID 02
ratbag debug: HID report ID 03
ratbag debug: HID report ID 10
ratbag debug: HID report ID 11
ratbag debug: HID report ID 20
ratbag debug: HID report ID 21
ratbag debug: 'Logitech MX Vertical' is using protocol v4.5
ratbag debug: device battery level is 50% (next 20%), status 0 
ratbag debug: device has programmable keys/buttons
ratbag debug: device has 7 buttons
ratbag debug: device has adjustable dpi
ratbag debug: device is at 1000 dpi (variable between 400 and 4000).
ratbag debug: device is at 1000 dpi (variable between 400 and 4000).
ratbag debug: device has 7 buttons
ratbag debug: driver match found: Logitech HID++2.0
hidraw5: "Logitech MX Vertical", 1 profiles
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 046d:c52b

```

**Comment by whot** [comment]
> $sudo ratbagctl hooting-chinchilla info

fwiw, the code names only need to be used when there's no unique-enough match otherwise, i.e. in your case your could  use "MX Vertical" or something that `strstr()` can find.

**Comment by FFY00** [comment]
@Noh3choo can you share more details? I haven't had any luck with the MX Vertical.

**Comment by Noh3choo** [comment]
No luck, I just have to assume support isnt there on the backend.

**Comment by FFY00** [comment]
I mean, it should work. I need to explore the issue. This is probably a bug in libratbag's implementation of the HID++ protocol.

**Comment by FFY00** [comment]
It works under Linux 5.2. I'll send a patch.
